### ISSUE TITLE
Can you share for me docker-compose for setup kafka?

### ISSUE THREAD

**Issue by nguyendkn** [crjenni21/Creos.KafkaHelper#6]
Can you share for me docker-compose for setup kafka?
- Config brokers
- Config Producers
- Config Consumers

**Comment by crjenni21** [comment]
Hey - thanks for your question.
This library is intended to simplify the Producing and Consuming from Kafka and assumes that a Kafka Cluster is already in place.  There are many sites to assist in getting a Kafka instance stood up while running locally or even on a series of VMs. And each implementation has several different options to meet your specific use-case in a development or even production environment.
